
"""
A schema for an e-invoicing integration application.
"""
type InvoiceSubmission @table(name: "invoiceSubmissions") {
  submissionDate: DateTime!
  invoiceData: String!
  status: String!
  hkaResponseId: String
}

type HKAResponse @table(name: "hkaResponses") {
  responseDate: DateTime!
  statusCode: Int!
  responseBody: String!
  invoiceSubmissionId: String
}

type Configuration @table(name: "configurations") {
  companyName: String!
  taxId: String!
  fiscalAddress: String!
  demoEnabled: Boolean!
  demoTokenEmpresa: String!
  demoTokenPassword: String!
  prodEnabled: Boolean!
  prodTokenEmpresa: String!
  prodTokenPassword: String!
}

type User @table(name: "users") {
  email: String! @unique
  companyName: String
  role: String
}
