type InvoiceSubmission @table {
  submissionDate: String!
  invoiceData: String!
  status: String!
  hkaResponseId: String
}

type User @table {
  email: String!
  companyName: String!
  role: String!
}

type Configuration @table {
  companyId: String
  settingKey: String!
  settingValue: String!
}

type HKAResponse @table {
  responseDate: String!
  statusCode: Int!
  responseBody: String!
  invoiceSubmissionId: String
}

type Query {
  listInvoiceSubmissions: [InvoiceSubmission] @permission(public: true)
  listUsers: [User] @permission(public: true)
}
